/**
 * Daily plan: one entry per day. Each day has resources (paths relative to month base) and optional activity.
 * Videos/songs/flashcards are arrays of file paths; activity is a single object { pdf, video, name } or null.
 */
const DAILY_PLAN = [
  // ----- MONTH 1: ACTION VERBS (Days 1–22) -----
  { monthId: 1, dayInMonth: 1, title: 'Learn Verbs #1', videos: ['Video/1. Learn Verbs #1.mp4'], songs: ['MP3/Learn Verbs #1.mp3'], flashcards: ['Flashcard tháng 1/verbs-flashcards-everyday-english-1.pdf'], activity: null },
  { monthId: 1, dayInMonth: 2, title: 'Learn Verbs #2', videos: ['Video/2. Learn Verbs #2.mp4'], songs: ['MP3/Learn Verbs #2.mp3'], flashcards: ['Flashcard tháng 1/verbs-flashcards-everyday-english-2.pdf'], activity: null },
  { monthId: 1, dayInMonth: 3, title: 'Learn Verbs #3', videos: ['Video/3.Learn Verbs #3.mp4'], songs: ['MP3/Learn Verbs #3.mp3'], flashcards: ['Flashcard tháng 1/verbs-flashcards-everyday-english-3.pdf'], activity: null },
  { monthId: 1, dayInMonth: 4, title: 'What Do You Like to Do?', videos: ['Video/4. What Do You Like to Do.mp4'], songs: ['MP3/What Do You Like to Do.mp3'], flashcards: ['Flashcard tháng 1/what-do-you-want-to-do-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 5, title: 'What Do You Want to Do?', videos: ['Video/5. What Do You Want to Do 1.mp4', 'Video/5. What Do You Want to Do 2.mp4'], songs: ['MP3/What Do You Want to Do.mp3'], flashcards: ['Flashcard tháng 1/what-do-you-want-to-do-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 6, title: 'What Can You Do?', videos: ['Video/6. What Can You Do  1.mp4', 'Video/6. What Can You Do 2.mp4'], songs: ['MP3/What Can You Do.mp3'], flashcards: ['Flashcard tháng 1/what-can-you-do-song-flashcards.pdf', 'Flashcard tháng 1/what can you do-flashcards.pdf'], activity: { pdf: 'Activity/what-can-you-do-activity.pdf', video: null, name: 'What Can You Do' } },
  { monthId: 1, dayInMonth: 7, title: 'Jump Up High!', videos: ['Video/7. Jump Up High 1.mp4', 'Video/7. Jump Up High 2.mp4', 'Video/7. Jump Around.mp4'], songs: ['MP3/Jump Up High!.mp3', 'MP3/Jump Around.mp3'], flashcards: ['Flashcard tháng 1/jump-up-high-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 8, title: 'Magic Wand Song', videos: ['Video/8 Magic Wand Song.mp4'], songs: ['MP3/Magic Wand 1.mp3', 'MP3/Magic Wand 2.mp3'], flashcards: ['Flashcard tháng 1/magic-wand-song-flashcards.pdf', 'Flashcard tháng 1/magic-wand-song-2-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 9, title: 'I Have a Bad Cold', videos: ['Video/9. I Have a Bad Cold.mp4'], songs: ['MP3/I Have a Bad Cold.mp3'], flashcards: ['Flashcard tháng 1/i-have-a-bad-cold-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 10, title: 'How Are You Today?', videos: ['Video/10. How Are You Today 1.mp4', 'Video/10. How Are You Today 2.mp4'], songs: ['MP3/How Are You Today #1 (1).mp3', 'MP3/How Are You Today #2.mp3'], flashcards: ['Flashcard tháng 1/how-are-you-today-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 11, title: 'Christmas Verbs', videos: ['Video/11. Learn Christmas  Verbs.mp4'], songs: ['MP3/Learn Christmas Verbs.mp3'], flashcards: ['Flashcard tháng 1/christmas-verbs-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 12, title: 'Octopus Song', videos: ['Video/12. Octopus Song.mp4'], songs: ['MP3/Octopus.mp3'], flashcards: ['Flashcard tháng 1/octopus-song-flashcards.pdf'], activity: { pdf: 'Activity/octopus-sing-and-play.pdf', video: 'Activity/Octopus - Sing and Play.mp4', name: 'Octopus - Sing and Play' } },
  { monthId: 1, dayInMonth: 13, title: 'Open, Close', videos: ['Video/13. Open, Close 1.mp4', 'Video/13. Open, Close 2.mp4'], songs: ['MP3/Open, Close.mp3'], flashcards: ['Flashcard tháng 1/open-close-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 14, title: 'Shake, Shake', videos: ['Video/14. Shake, Shake 1.mp4'], songs: ['MP3/Shake, Shake.mp3'], flashcards: ['Flashcard tháng 1/shake-shake-song.pdf'], activity: null },
  { monthId: 1, dayInMonth: 15, title: 'Skeleton Song', videos: ['Video/15. Skeleton Skeleton 1.mp4', 'Video/15. Skeleton, Skeleton 2.mp4'], songs: ['MP3/Skeleton Skeleton.mp3'], flashcards: ['Flashcard tháng 1/skeleton-skeleton-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 16, title: 'Incy Wincy Spider', videos: ['Video/16 Incy Wincy Spider 1.mp4'], songs: ['MP3/Spider Song.mp3'], flashcards: ['Flashcard tháng 1/spider-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 17, title: 'Teddy Bear', videos: ['Video/17.Teddy Bear 1.mp4'], songs: ['MP3/Teddy Bear.mp3'], flashcards: ['Flashcard tháng 1/teddy-bear-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 18, title: 'Touch Your Head', videos: ['Video/18. Touch Your Head 1.mp4'], songs: ['MP3/Touch Your Head.mp3'], flashcards: ['Flashcard tháng 1/touch-your-head-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 19, title: 'Can You Play the Drums?', videos: ['Video/19. Can You Play the Drums 1.mp4', 'Video/19. Can You Play The Drums 2.mp4'], songs: ['MP3/Can You Play the Drums.mp3'], flashcards: ['Flashcard tháng 1/can-you-play-the-drums-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 20, title: 'Cookies for Santa', videos: ['Video/20. Let_s Make Cookies for Santa Claus.mp4'], songs: ['MP3/Lets Make Cookies for Santa Claus.mp3'], flashcards: ['Flashcard tháng 1/lets-make-cookies-for-santa-claus-song-flashcards.pdf'], activity: null },
  { monthId: 1, dayInMonth: 21, title: 'The Walking Song & Feelings', videos: ['Video/21.The Walking Song.mp4', 'Video/22. Feelings - Talking Flashcards.mp4'], songs: ['MP3/The Walking Song.mp3'], flashcards: [], activity: null },
  { monthId: 1, dayInMonth: 22, title: 'Review Day – Color the Fish', videos: [], songs: [], flashcards: [], activity: { pdf: 'Activity/color-the-fish-activity.pdf', video: 'Activity/color-the-fish activity.mp4', name: 'Color the Fish' } },

  // ----- MONTH 2: ANIMALS (Days 1–15 sample) -----
  { monthId: 2, dayInMonth: 1, title: 'Aquarium Animals 1', videos: ['Video/1. Aquarium animals  1.mp4'], songs: ['MP3/1. Aquarium animals  1.mp3'], flashcards: ['Flashcard/aquarium-animal-flashcards.pdf'], activity: null },
  { monthId: 2, dayInMonth: 2, title: 'Aquarium Animals 2 & 3', videos: ['Video/2. Aquarium Animals 2.mp4', 'Video/3. Aquarium Animals  3.mp4'], songs: ['MP3/2. Aquarium Animals 2.mp3', 'MP3/3. Aquarium Animals  3.mp3'], flashcards: ['Flashcard/aquarium-animal-flashcards.pdf'], activity: null },
  { monthId: 2, dayInMonth: 3, title: 'Insects & Bugs', videos: ['Video/4. Insects.mp4', 'Video/4.1 Butterfly Song 1.mp4', 'Video/4.2 I Love Bugs!.mp4'], songs: ['MP3/4 Learn Insects.mp3', 'MP3/4.1 Bugs.mp3', 'MP3/4.2 Butterfly Song 1.mp3'], flashcards: ['Flashcard/insect-flashcards.pdf', 'Flashcard/butterfly-song-flashcards.pdf'], activity: null },
  { monthId: 2, dayInMonth: 4, title: 'Butterfly & Zoo Animals', videos: ['Video/5. Butterfly Song 2.mp4', 'Video/5.1 Learn Bugs Vocabulary - Talking Flashcards.mp4', 'Video/6. Zoo Animals.mp4'], songs: ['MP3/5. Butterfly Song 2.mp3', 'MP3/6. Zoo Animals.mp3'], flashcards: ['Flashcard/Zoo Animals flashcards.pdf'], activity: null },
  { monthId: 2, dayInMonth: 5, title: 'Animal Song & Forest Dance', videos: ['Video/7. The Animal Song.mp4', 'Video/8. Forest Dance.mp4'], songs: ['MP3/7. The Animal Song.mp3', 'MP3/8. Forest Dance.mp3'], flashcards: ['Flashcard/the-animal-song-flashcards.pdf', 'Flashcard/the-forest-dance-song-flashcards.pdf'], activity: null },
  { monthId: 2, dayInMonth: 6, title: 'Let\'s Go to the Zoo', videos: ['Video/9. Let_s Go To the Zoo 1.mp4', 'Video/10. Let_s Go To The zoo  2.mp4'], songs: ['MP3/9. Let_s Go To the Zoo 1.mp3', 'MP3/10. Let_s Go To The zoo  2.mp3'], flashcards: [], activity: null },
  { monthId: 2, dayInMonth: 7, title: 'Let\'s Go to the Farm', videos: ['Video/11. Lets Go to the Farm 1.mp4', 'Video/12. Let_s Go To The Farm 2.mp4'], songs: ['MP3/11. Lets Go to the Farm 1.mp3', 'MP3/12. Let_s Go To The Farm 2.mp3'], flashcards: ['Flashcard/Farm Animals Flashcard.pdf'], activity: { pdf: 'Activity Tháng 2/Farm Animal Activity.pdf', video: 'Activity Tháng 2/Farm Animal Activity.mp4', name: 'Farm Animal Activity' } },
  { monthId: 2, dayInMonth: 8, title: 'Octopus & Spider', videos: ['Video/13. Octopus 1.mp4', 'Video/14. The Octopus Song 2.mp4', 'Video/15. Spider Song.mp4'], songs: ['MP3/13. Octopus 1.mp3', 'MP3/14. The Octopus Song 2.mp3', 'MP3/15. Spider Song.mp3'], flashcards: ['Flashcard/octopus-song-flashcards- DA CO KO IN.pdf'], activity: null },
  { monthId: 2, dayInMonth: 9, title: 'The Beach', videos: ['Video/16. The Beach.mp4', 'Video/17. The Beach 2.mp4'], songs: ['MP3/16. The Beach.mp3', 'MP3/17. The Beach 2.mp3'], flashcards: ['Flashcard/the-beach-song-flashcards.pdf'], activity: null },
  { monthId: 2, dayInMonth: 10, title: 'Teddy Bear & Snail', videos: ['Video/18. Teddy Bear.mp4', 'Video/19.The Snail Song.mp4'], songs: ['MP3/18. Teddy Bear.mp3', 'MP3/23. Snail Song.mp3'], flashcards: ['Flashcard/teddy-bear-song-flashcards-da co, khong in.pdf'], activity: null },
  { monthId: 2, dayInMonth: 11, title: 'Three Ladybugs & Forest', videos: ['Video/20. Three Ladybugs 1.mp4', 'Video/21. Three Ladybugs 2.mp4', 'Video/22.Forest Animals - Talking Flashcards.mp4'], songs: ['MP3/21. Three Ladybugs 1.mp3', 'MP3/22. Three Ladybugs 2.mp3'], flashcards: ['Flashcard/three-ladybugs-song-flashcards.pdf'], activity: null },
  { monthId: 2, dayInMonth: 12, title: 'Review & Games', videos: [], songs: [], flashcards: [], activity: null, games: ['Game Tháng 2/Animal Dominoes Game for Kids.pdf', 'Game Tháng 2/fishing-game.pdf'] },

  // ----- MONTH 3: AROUND THE HOUSE (Days 1–11) -----
  { monthId: 3, dayInMonth: 1, title: 'My House', videos: ['Video/1. My House - Talking Flashcards.mp4'], songs: ['Mp3 Tháng 3/1.My House - Talking Flashcards.mp3'], flashcards: [], activity: null },
  { monthId: 3, dayInMonth: 2, title: 'Rooms of the House', videos: ['Video/2. Learn Rooms of the House - Talking Flashcards.mp4'], songs: ['Mp3 Tháng 3/2. Learn Rooms of the House - Talking Flashcards.mp3'], flashcards: ['Flashcard Tháng 3/3. rooms-of-the-house-flashcards.pdf'], activity: null },
  { monthId: 3, dayInMonth: 3, title: 'Living Room', videos: ['Video/3. Learn Living Room Vocabulary - Talking Flashcards.mp4'], songs: ['Mp3 Tháng 3/3. Learn Living Room Vocabulary - Talking Flashcards.mp3'], flashcards: ['Flashcard Tháng 3/2. living-room-flashcards.pdf'], activity: null },
  { monthId: 3, dayInMonth: 4, title: 'Bedroom', videos: ['Video/4. Learn Bedroom Vocabulary - Talking Flashcards.mp4'], songs: ['Mp3 Tháng 3/4. Learn Bedroom Vocabulary - Talking Flashcards.mp3'], flashcards: ['Flashcard Tháng 3/4. bedroom-flashcards.pdf'], activity: null },
  { monthId: 3, dayInMonth: 5, title: 'Dining & Kitchen', videos: ['Video/5. Learn Dining Room Vocabulary _ Talking Flashcards.mp4', 'Video/6. Learn Kitchen Items - Talking Flashcards.mp4'], songs: ['Mp3 Tháng 3/5. Learn Dining Room Vocabulary - Talking Flashcards.mp3', 'Mp3 Tháng 3/6. Learn Kitchen Items - Talking Flashcards.mp3'], flashcards: ['Flashcard Tháng 3/5. dining-room-flashcards.pdf', 'Flashcard Tháng 3/6. kitchen-items-flashcards.pdf'], activity: null },
  { monthId: 3, dayInMonth: 6, title: 'Bathroom & Garage', videos: ['Video/7. Learn Bathroom Items - Talking Flashcards.mp4', 'Video/8. Learn Garage Vocabulary _ Talking Flashcards.mp4'], songs: ['Mp3 Tháng 3/7. Learn Bathroom Items - Talking Flashcards.mp3', 'Mp3 Tháng 3/8. Learn Garage Vocabulary - Talking Flashcards.mp3'], flashcards: ['Flashcard Tháng 3/7. bathroom-flashcards.pdf', 'Flashcard Tháng 3/8. garage-flashcards.pdf'], activity: null },
  { monthId: 3, dayInMonth: 7, title: 'Kid\'s Bedroom & Laundry', videos: ['Video/9. Learn Kid_s Bedroom Vocabulary - Talking Flashcards.mp4', 'Video/10. Learn Laundry Room Vocabulary - Talking Flashcards.mp4'], songs: ['Mp3 Tháng 3/9. Learn Kid_s Bedroom Vocabulary - Talking Flashcards.mp3', 'Mp3 Tháng 3/10. Learn Laundry Room Vocabulary.mp3'], flashcards: ['Flashcard Tháng 3/9. kids-bedroom-flashcards.pdf', 'Flashcard Tháng 3/10. laundry-room-flashcards.pdf'], activity: null },
  { monthId: 3, dayInMonth: 8, title: 'Around the House Review', videos: ['Video/11. Around The House - Talking Flashcards.mp4'], songs: ['Mp3 Tháng 3/11. Around The House - Talking Flashcards.mp3'], flashcards: [], activity: null }
];
